// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIImRzdhxtxv6A6arp_vy-Fex61dCREo',
    appId: '1:436089060:web:9fa6b1ba240ff1efc73cf1',
    messagingSenderId: '436089060',
    projectId: 'teamvortexdb-16b33',
    authDomain: 'teamvortexdb-16b33.firebaseapp.com',
    storageBucket: 'teamvortexdb-16b33.appspot.com',
    measurementId: 'G-952FJDY0XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkG7Pj0TKKUhOjN-JFZPhutokFS_4HltY',
    appId: '1:436089060:android:df3473ab7669c17cc73cf1',
    messagingSenderId: '436089060',
    projectId: 'teamvortexdb-16b33',
    storageBucket: 'teamvortexdb-16b33.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIImRzdhxtxv6A6arp_vy-Fex61dCREo',
    appId: '1:436089060:web:022e5f8edd139ed0c73cf1',
    messagingSenderId: '436089060',
    projectId: 'teamvortexdb-16b33',
    authDomain: 'teamvortexdb-16b33.firebaseapp.com',
    storageBucket: 'teamvortexdb-16b33.appspot.com',
    measurementId: 'G-0PVE57J71Y',
  );
}
